### ISSUE TITLE
请求更新插件

### ISSUE THREAD

**Issue by wlz-remake** [CCYellowStar/zhenxun_plugin_TextToPic#3]
文心那边已经支持了更多修饰词和图片尺寸，希望插件能同步
![image](https://user-images.githubusercontent.com/105090141/194082811-331a336e-e702-4b59-80d6-972904dfda12.png)

**Comment by CCYellowStar** [comment]
你可以直接使用对应关键词

**Comment by CCYellowStar** [comment]
![image](https://user-images.githubusercontent.com/47291058/194084068-81758c40-2893-4091-99a6-abfe7ddcca76.png)
反正风格是可以用的
