### ISSUE TITLE
一直出错了。

### ISSUE THREAD

**Issue by mozicha** [CCYellowStar/zhenxun_plugin_TextToPic#4]
![image](https://user-images.githubusercontent.com/105711939/194316424-0b16c0fc-0807-4173-934c-0384405af29d.png)
![image](https://user-images.githubusercontent.com/105711939/194316551-b07bfd1b-480e-4b20-b3ec-6c1a29acf88e.png)

**Comment by CCYellowStar** [comment]
检查下api有没有填反了

**Comment by CCYellowStar** [comment]
你再申请一个试试

**Comment by mozicha** [comment]
可以

**Comment by mozicha** [comment]
我开的全局代理有影响吗

**Comment by CCYellowStar** [comment]
你是刚下的插件吗

**Comment by mozicha** [comment]
嗯

**Comment by mozicha** [comment]
。。就是全局的问题

**Comment by CCYellowStar** [comment]
那你用回新版吧

**Comment by CCYellowStar** [comment]
应该没必要开全局吧，代理填对就行
