### ISSUE TITLE
yaml处没有生成配置

### ISSUE THREAD

**Issue by inkbloom** [CCYellowStar/zhenxun_plugin_TextToPic#5]
bot运行时插件处可以看到成功启动了  发指令机器人也有回复  但yaml没生成配置 我自己加了条后机器人还是报错没ak和sk

**Comment by CCYellowStar** [comment]
![image](https://user-images.githubusercontent.com/47291058/194759539-f1e85d4d-3f1c-4041-86fe-fc4ba2d2f930.png)
看看这个文件下面能不能翻到我的插件名字

**Comment by inkbloom** [comment]
> ![image](https://user-images.githubusercontent.com/47291058/194759539-f1e85d4d-3f1c-4041-86fe-fc4ba2d2f930.png)
> 看看这个文件下面能不能翻到我的插件名字

能 在最后

**Comment by CCYellowStar** [comment]
我那段删掉，让他重新生成

**Comment by inkbloom** [comment]
> 我那段删掉，让他重新生成

重新生成还是没有 只有data里的有![IMG_20221009_213705.jpg](https://user-images.githubusercontent.com/45934514/194760009-656427ca-4d3c-41ab-89d3-4773a784adf2.jpg)

**Comment by CCYellowStar** [comment]
你的配置文件正常吗，那些项会不会都是空的

**Comment by inkbloom** [comment]
> 你的配置文件正常吗，那些项会不会都是空的

bot的基础配置吗 都是正常的

**Comment by CCYellowStar** [comment]
你直接填date里呢

**Comment by CCYellowStar** [comment]
我总感觉你的yaml上面都是空的

**Comment by inkbloom** [comment]
> 我总感觉你的yaml上面都是空的

我上面识图插件的ak填上就没问题  这个不行😭

**Comment by inkbloom** [comment]
> 你直接填date里呢

直接加data 重启bot时 自动把data里的有重新生成了  ak sk又空了

**Comment by CCYellowStar** [comment]
那你填代码里算了

**Comment by CCYellowStar** [comment]
![image](https://user-images.githubusercontent.com/47291058/194760689-0c419108-78fd-48a6-bf23-f8e92263e903.png)

**Comment by inkbloom** [comment]
> 那你填代码里算了
> 

嗯 我去代码里找找位置

**Comment by CCYellowStar** [comment]
然后也把data删了

**Comment by inkbloom** [comment]
> ![image](https://user-images.githubusercontent.com/47291058/194760689-0c419108-78fd-48a6-bf23-f8e92263e903.png)
> 

要引号吗 单双引 我双引提示还是没ak sk 不加引号就插件保存

**Comment by CCYellowStar** [comment]
![image](https://user-images.githubusercontent.com/47291058/194761138-67d0044b-d2ba-4fe6-9991-6f2b6a79fb4b.png)
你写这个算了，加双引号
