### ISSUE TITLE
"style is error"

### ISSUE THREAD

**Issue by kuai364354200** [CCYellowStar/zhenxun_plugin_TextToPic#7]
出错了！<class 'wenxin_api.error.APIError'>：{
  "code": 4003,
  "msg": "style is error",
  "data": {
    "requestId": "8862b4289c05e5a8f39e8988b8db49ea"
  }
}

![图片](https://user-images.githubusercontent.com/72508741/205460901-c23ad33c-81ea-47c4-aea0-c3950e4fdddd.png)

**Comment by kuai364354200** [comment]
哦哦“卡通”改成“二次元”了，被readme的图片误导了

**Comment by PackageInstaller** [comment]
哈哈哈，我也是这个，给我看不会了

**Comment by KnightKilito** [comment]
哈哈哈原来是这样
